In [2]:
import numpy as np 
import pandas as pd

In [53]:
df = pd.read_csv('/Users/colin/Downloads/IDX Exchange/raw/CRMLSSold202603.csv')

df.head(10)
df['ListingKey'].head()

0    1156815844
1    1156789232
2    1156759650
3    1156727153
4    1156726807
Name: ListingKey, dtype: int64

In [54]:


dct = {name: 0 for name in df.columns}

print(dct)

# pct null per column
for col in df:
    dct[col] = round((int(df[col].isna().sum()) / len(df[col])) * 100, 2)

print(dct)

{'BuyerAgentAOR': 0, 'ListAgentAOR': 0, 'Flooring': 0, 'ViewYN': 0, 'WaterfrontYN': 0, 'BasementYN': 0, 'PoolPrivateYN': 0, 'OriginalListPrice': 0, 'ListingKey': 0, 'CloseDate': 0, 'ClosePrice': 0, 'ListAgentFirstName': 0, 'ListAgentLastName': 0, 'Latitude': 0, 'Longitude': 0, 'UnparsedAddress': 0, 'PropertyType': 0, 'LivingArea': 0, 'ListPrice': 0, 'DaysOnMarket': 0, 'ListOfficeName': 0, 'BuyerOfficeName': 0, 'CoListOfficeName': 0, 'ListAgentFullName': 0, 'CoListAgentFirstName': 0, 'CoListAgentLastName': 0, 'BuyerAgentMlsId': 0, 'BuyerAgentFirstName': 0, 'BuyerAgentLastName': 0, 'FireplacesTotal': 0, 'AssociationFeeFrequency': 0, 'AboveGradeFinishedArea': 0, 'ListingKeyNumeric': 0, 'MLSAreaMajor': 0, 'TaxAnnualAmount': 0, 'CountyOrParish': 0, 'MlsStatus': 0, 'ElementarySchool': 0, 'AttachedGarageYN': 0, 'ParkingTotal': 0, 'BuilderName': 0, 'PropertySubType': 0, 'LotSizeAcres': 0, 'SubdivisionName': 0, 'BuyerOfficeAOR': 0, 'YearBuilt': 0, 'StreetNumberNumeric': 0, 'ListingId': 0, 'BathroomsTotalInteger': 0, 'City': 0, 'TaxYear': 0, 'BuildingAreaTotal': 0, 'BedroomsTotal': 0, 'ContractStatusChangeDate': 0, 'ElementarySchoolDistrict': 0, 'CoBuyerAgentFirstName': 0, 'PurchaseContractDate': 0, 'ListingContractDate': 0, 'BelowGradeFinishedArea': 0, 'BusinessType': 0, 'StateOrProvince': 0, 'CoveredSpaces': 0, 'MiddleOrJuniorSchool': 0, 'FireplaceYN': 0, 'Stories': 0, 'HighSchool': 0, 'Levels': 0, 'LotSizeDimensions': 0, 'LotSizeArea': 0, 'MainLevelBedrooms': 0, 'NewConstructionYN': 0, 'GarageSpaces': 0, 'HighSchoolDistrict': 0, 'PostalCode': 0, 'AssociationFee': 0, 'LotSizeSquareFeet': 0, 'MiddleOrJuniorSchoolDistrict': 0, 'OriginatingSystemName': 0, 'OriginatingSystemSubName': 0}
{'BuyerAgentAOR': 8.48, 'ListAgentAOR': 0.05, 'Flooring': 41.71, 'ViewYN': 9.53, 'WaterfrontYN': 99.96, 'BasementYN': 98.48, 'PoolPrivateYN': 10.87, 'OriginalListPrice': 0.32, 'ListingKey': 0.0, 'CloseDate': 0.0, 'ClosePrice': 0.0, 'ListAgentFirstName': 0.44, 'ListAgentLastName': 0.01, 'Latitude': 1.04, 'Longitude': 0.98, 'UnparsedAddress': 0.17, 'PropertyType': 0.0, 'LivingArea': 6.88, 'ListPrice': 0.15, 'DaysOnMarket': 0.0, 'ListOfficeName': 0.0, 'BuyerOfficeName': 0.85, 'CoListOfficeName': 78.73, 'ListAgentFullName': 0.06, 'CoListAgentFirstName': 78.81, 'CoListAgentLastName': 78.75, 'BuyerAgentMlsId': 0.46, 'BuyerAgentFirstName': 0.33, 'BuyerAgentLastName': 0.06, 'FireplacesTotal': 100.0, 'AssociationFeeFrequency': 69.36, 'AboveGradeFinishedArea': 100.0, 'ListingKeyNumeric': 0.0, 'MLSAreaMajor': 10.8, 'TaxAnnualAmount': 99.7, 'CountyOrParish': 0.0, 'MlsStatus': 0.0, 'ElementarySchool': 89.93, 'AttachedGarageYN': 28.24, 'ParkingTotal': 2.88, 'BuilderName': 96.11, 'PropertySubType': 7.62, 'LotSizeAcres': 8.37, 'SubdivisionName': 63.45, 'BuyerOfficeAOR': 8.94, 'YearBuilt': 4.36, 'StreetNumberNumeric': 0.25, 'ListingId': 0.0, 'BathroomsTotalInteger': 4.38, 'City': 0.0, 'TaxYear': 99.94, 'BuildingAreaTotal': 86.94, 'BedroomsTotal': 6.37, 'ContractStatusChangeDate': 0.0, 'ElementarySchoolDistrict': 100.0, 'CoBuyerAgentFirstName': 91.62, 'PurchaseContractDate': 2.03, 'ListingContractDate': 0.02, 'BelowGradeFinishedArea': 99.55, 'BusinessType': 99.74, 'StateOrProvince': 0.0, 'CoveredSpaces': 100.0, 'MiddleOrJuniorSchool': 89.95, 'FireplaceYN': 8.61, 'Stories': 18.12, 'HighSchool': 86.51, 'Levels': 12.02, 'LotSizeDimensions': 94.74, 'LotSizeArea': 8.04, 'MainLevelBedrooms': 45.84, 'NewConstructionYN': 11.91, 'GarageSpaces': 12.9, 'HighSchoolDistrict': 34.15, 'PostalCode': 0.04, 'AssociationFee': 29.57, 'LotSizeSquareFeet': 8.12, 'MiddleOrJuniorSchoolDistrict': 100.0, 'OriginatingSystemName': 0.0, 'OriginatingSystemSubName': 0.0}

In [61]:
df1 = pd.to_datetime(df['ListingContractDate'].copy(), errors = 'coerce')
df1.head()

df2 = pd.to_datetime(df['CloseDate'])
df2.dt.year.head()

0    2026
1    2026
2    2026
3    2026
4    2026
Name: CloseDate, dtype: int32

In [ ]:
sold = pd.read_csv("sold_final.csv", low_memory=False)
listed = pd.read_csv("listed_final.csv", low_memory=False)

# converting to pandas datetimes
sold["CloseDate"] = pd.to_datetime(sold["CloseDate"], errors="coerce")
sold["ListingContractDate"] = pd.to_datetime(sold["ListingContractDate"], errors="coerce")
sold["PurchaseContractDate"] = pd.to_datetime(sold["PurchaseContractDate"], errors="coerce")
listed["ListingContractDate"] = pd.to_datetime(listed["ListingContractDate"], errors="coerce")

print(f"\nShape: {sold.shape}")
print(f"Rows: {sold.shape[0]}, Columns: {sold.shape[1]}")
print(f"\nColumn dtypes:\n{sold.dtypes.value_counts()}")

Shape: (397206, 89)
Rows: 397206, Columns: 89

Column dtypes:
object            49
float64           32
int64              5
datetime64[ns]     3
Name: count, dtype: int64
BuyerAgentAOR     12.35
ListAgentAOR      11.62
Flooring          35.84
ViewYN             8.52
WaterfrontYN      99.94
                  ...
price_per_sqft     0.06
days_to_close      0.00
year               0.00
month              0.00
property_age       0.09
Length: 89, dtype: float64

In [ ]:
# null analysis

missing = sold.isnull().sum()
missing_pct = round(missing / len(sold) * 100, 2)
missing_pct2 = (missing / len(sold) * 100).round(2)
print(missing_pct)
print(missing_pct2)

BuyerAgentAOR     12.35
ListAgentAOR      11.62
Flooring          35.84
ViewYN             8.52
WaterfrontYN      99.94
                  ...
price_per_sqft     0.06
days_to_close      0.00
year               0.00
month              0.00
property_age       0.09
Length: 89, dtype: float64
BuyerAgentAOR     12.35
ListAgentAOR      11.62
Flooring          35.84
ViewYN             8.52
WaterfrontYN      99.94
                  ...
price_per_sqft     0.06
days_to_close      0.00
year               0.00
month              0.00
property_age       0.09
Length: 89, dtype: float64

In [ ]:
df_listed_enriched = pd.read_csv('listed_enriched.csv')
df_sold_enriched = pd.read_csv('sold_enriched.csv')

/var/folders/zn/h8q2ztjx1dx0kx0hl7y57pdh0000gn/T/ipykernel_36567/3182049283.py:1: DtypeWarning: Columns (2,32,43,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listed_enriched = pd.read_csv('listed_enriched.csv')
/var/folders/zn/h8q2ztjx1dx0kx0hl7y57pdh0000gn/T/ipykernel_36567/3182049283.py:2: DtypeWarning: Columns (0,1,4,9,64,78,79,80,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_enriched = pd.read_csv('sold_enriched.csv')

In [4]:
df_listed_enriched.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,price_per_sqft,year,month,property_age,year_month,rate_30yr_fixed
0,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704,1029.976941,2024,1,60.0,2024-01,6.6425
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,254.00,5300.0,NaN,16 Palisades,896.700143,2024,1,30.0,2024-01,6.6425
2,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,9404.0,NaN,1615 Waverly Road,969.230769,2024,1,59.0,2024-01,6.6425
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaN,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,295.95,58232.0,NaN,2250 Indian Creek Road,414.431330,2024,1,21.0,2024-01,6.6425
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaN,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,0.00,2250.0,NaN,317 E. Bayfront,5482.550625,2024,1,5.0,2024-01,6.6425

In [5]:
df_sold_enriched.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,BuyerAgencyCompensation,latfilled,lonfilled,price_per_sqft,days_to_close,year,month,property_age,year_month,rate_30yr_fixed
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,NaN,210.526316,842.0,2024,1,36.0,2024-01,6.6425
1,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,NaN,NaN,NaN,412.867275,1033.0,2024,1,1.0,2024-01,6.6425
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,NaN,NaN,NaN,410.334347,1033.0,2024,1,1.0,2024-01,6.6425
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,NaN,NaN,NaN,430.075188,0.0,2024,1,65.0,2024-01,6.6425
4,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,NaN,NaN,NaN,591.891046,0.0,2024,1,69.0,2024-01,6.6425

In [6]:
df_sold_cleaned = pd.read_csv('sold_cleaned.csv')
df_listed_cleaned = pd.read_csv('listed_cleaned.csv')

/var/folders/zn/h8q2ztjx1dx0kx0hl7y57pdh0000gn/T/ipykernel_36567/3340602915.py:1: DtypeWarning: Columns (0,1,7,51,63,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_cleaned = pd.read_csv('sold_cleaned.csv')
/var/folders/zn/h8q2ztjx1dx0kx0hl7y57pdh0000gn/T/ipykernel_36567/3340602915.py:2: DtypeWarning: Columns (2,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listed_cleaned = pd.read_csv('listed_cleaned.csv')